/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        surface: "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#44474d",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        outline: "#75777e",
        "outline-variant": "#c5c6cd",
        "surface-tint": "#515f78",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#0d1c32",
        "on-primary-container": "#76849f",
        "inverse-primary": "#b9c7e4",
        secondary: "#006b5f",
        "on-secondary": "#ffffff",
        "secondary-container": "#62fae3",
        "on-secondary-container": "#007165",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2b1701",
        "on-tertiary-container": "#9f7d5b",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#b9c7e4",
        "on-primary-fixed": "#0d1c32",
        "on-primary-fixed-variant": "#39475f",
        "secondary-fixed": "#62fae3",
        "secondary-fixed-dim": "#3cddc7",
        "on-secondary-fixed": "#00201c",
        "on-secondary-fixed-variant": "#005047",
        "tertiary-fixed": "#ffdcbd",
        "tertiary-fixed-dim": "#e7bf99",
        "on-tertiary-fixed": "#2b1701",
        "on-tertiary-fixed-variant": "#5d4124",
        background: "#f7f9fb",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-margin": "24px",
        gutter: "16px",
        unit: "4px",
        "desktop-max": "1440px",
      },
      fontFamily: {
        sans: ['"Inter"', '"PingFang SC"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-bold": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      maxWidth: {
        "desktop-max": "1440px",
      },
      boxShadow: {
        ambient: "0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -2px rgba(0, 0, 0, 0.05)",
        "ambient-dark": "0 10px 15px -3px rgba(0, 0, 0, 0.3)",
      },
    },
  },
  plugins: [],
};
